# -*- coding: utf-8 -*-
#!/usr/bin/env python
import os
import logging
import importlib

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "lms.envs.aws")
os.environ.setdefault("lms.envs.aws,SERVICE_VARIANT", "lms")
os.environ.setdefault("PATH", "/edx/app/edxapp/venvs/edxapp/bin:/edx/app/edxapp/edx-platform/bin:/edx/app/edxapp/.rbenv/bin:/edx/app/edxapp/.rbenv/shims:/edx/app/edxapp/.gem/bin:/edx/app/edxapp/edx-platform/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin")

os.environ.setdefault("SERVICE_VARIANT", "lms")
os.chdir("/edx/app/edxapp/edx-platform")

startup = importlib.import_module("lms.startup")
startup.run()

from django.contrib.auth.models import User
from student.models import UserProfile
from django.http import HttpResponseRedirect, JsonResponse
from enrollment.api import get_enrollments
from student.models import CourseEnrollment
from opaque_keys.edx.locations import SlashSeparatedCourseKey

log = logging.getLogger()

users_list_to_remail = {}

# users_list_to_remail = {
#     "f.doukar@cma-ain.fr":"fatima.doukar@cma-auvergnerhonealpes.fr",
#     "c.gemain@cma-ain.fr":"christine.gemain@cma-auvergnerhonealpes.fr",
#     "d.trindade@cma-ain.fr":"daphne.trindade@cma-auvergnerhonealpes.fr",
#     "roselise.peillon@cma-allier.fr":"roselise.peillon@cma-auvergnerhonealpes.fr",
#     "aurelie.jacquet@cma-allier.fr":"aurelie.jacquet@cma-auvergnerhonealpes.fr",
#     "stephanie.rouffineau@cma-auvergnerhonealpes.fr":"stephanie.rouffineau@cma-auvergnerhonealpes.fr",
#     "benoit.auclair@cma-allier.fr":"benoit.auclair@cma-auvergnerhonealpes.fr",
#     "yannis.boudina@cma-allier.fr":"yannis.boudina@cma-auvergnerhonealpes.fr",
#     "l.bulinge@cma-ardeche.fr":"lionel.bulinge@cma-auvergnerhonealpes.fr",
#     "f.perard@cma-ardeche.fr":"frederic.perard@cma-auvergnerhonealpes.fr",
#     "c.greffe@cma-ardeche.fr":"cecile.greffe@cma-auvergnerhonealpes.fr",
#     "c.jaeck@cma-ardeche.fr":"catherine.jaeck@cma-auvergnerhonealpes.fr",
#     "r.pic@cma-ardeche.fr":"regis.pic@cma-auvergnerhonealpes.fr",
#     "nathalie.cheyvialle@cma-cantal.fr":"nathalie.cheyvialle@cma-auvergnerhonealpes.fr",
#     "imartin@cma-aube.fr":"imartin@cma-grandest.fr",
#     "mruszkiewicz@cma-aube.fr":"mruszkiewicz@cma-grandest.fr",
#     "lcayron@cma-aube.fr":"lcayron@cma-grandest.fr",
#     "dtestard@cma-aube.fr":"dtestard@cma-grandest.fr",
#     "cmonticone@cma-aube.fr":"cmonticone@cma-grandest.fr",
#     "sgaribal@cmai-calvados-orne.fr":"sgaribal@cma-normandie.fr",
#     "bbabiy@cmai-calvados-orne.fr":"bbabiy@cma-normandie.fr",
#     "shardel@cmai-calvados-orne.fr":"shardel@cma-normandie.fr",
#     "sherve@cmai-calvados-orne.fr":"sherve@cma-normandie.fr",
#     "sgautier@cmai-calvados-orne.fr":"sgautier@cma-normandie.fr",
#     "camille.payen@cma-cantal.fr":"camille.payen@cma-auvergnerhonealpes.fr",
#     "cecile.guy@cma-cantal.fr":"cecile.guy@cma-auvergnerhonealpes.fr",
#     "gerard.veyrines@cma-cantal.fr":"gerard.veyrines@cma-auvergnerhonealpes.fr",
#     "anne.lipowicz@cma-cantal.fr":"anne.lipowicz@cma-auvergnerhonealpes.fr",
#     "x.ravel@cma-drome.fr":"xavier.ravel@cma-auvergnerhonesalpes.fr",
#     "sofie.perrot@cm-bourges.fr":"SPerrot@cma-cvl.fr",
#     "jb.prioul@cm-bourges.fr":"JBPrioul@cma-cvl.fr",
#     "fred.dauphin@cm-bourges.fr":"FDauphin@cma-cvl.fr",
#     "aude.humbert@cm-bourges.fr":"AHumbert@cma-cvl.fr",
#     "h.dauly@cma22.fr":"helene.dauly@cma-bretagne.fr",
#     "jp.philippe@cma22.fr":"jean-pierre.philippe@cma-bretagne.fr",
#     "jp.jehan@cma22.fr":"jean-pierre.jehan@cma-bretagne.fr",
#     "b.bergeronne@cma22.fr":"beatrice.bergeronne@cma-bretagne.fr",
#     "o.durand@cma22.fr":"olivier.durand@cma-bretagne.fr",
#     "i.richard@cma22.fr":"isabelle.richard@cma-bretagne.fr",
#     "c.bajul@cma22.fr":"corinne.bajul@cma-bretagne.fr",
#     "c.lux@cma22.fr":"christelle.lux@cma-bretagne.fr",
#     "sbuerick@artisanat-bourgogne.fr":"sbuerick@artisanat-bfc.fr",
#     "tvaccaro@artisanat-bourgogne.fr":"tvaccaro@artisanat-bfc.fr",
#     "nnoel@artisanat-bourgogne.fr":"nnoel@artisanat-bfc.fr",
#     "psimon@artisanat-bourgogne.fr":"psimon@artisanat-bfc.fr",
#     "mberger@artisanat-bourgogne.fr":"mberger@artisanat-bfc.fr",
#     "mhlesniewska@artisanat-bourgogne.fr":"mhlesniewska@artisanat-bfc.fr",
#     "eeichelbrenner@artisanat-bourgogne.fr":"eeichelbrenner@artisanat-bfc.fr",
#     "blatrille@artisanat-bourgogne.fr":"blatrille@artisanat-bfc.fr",
#     "vlaubier@artisanat-bourgogne.fr":"vlaubier@artisanat-bfc.fr",
#     "d.lombardet@artisanat-comtois.fr":"dlombardet@artisanat-bfc.fr",
#     "h.bibi@artisanat-comtois.fr":"hbibi@artisanat-bfc.fr",
#     "l.gourdon@cma-drome.fr":"ludovic.gourdon@cma-auvergnerhonesalpes.fr",
#     "n.ammarene@cma-drome.fr":"nicolas.ammarene@cma-auvergnerhonesalpes.fr",
#     "n.lapassat@cma-drome.fr":"nathalie.lapassat@cma-auvergnerhonesalpes.fr",
#     "m.schroder@cma-drome.fr":"marlène.schroder@cma-auvergnerhonesalpes.fr",
#     "e.mindren@cma-drome.fr":"estelle.mindren@cma-auvergnerhonesalpes.fr",
#     "l.cane@cma-drome.fr":"laetitia.cane@cma-auvergnerhonesalpes.fr",
#     "cma.simard@artisanat91.fr":"virginie.vallee@cma-idf.fr",
#     "cma.tris@artisanat91.fr":"ludovic.tris@cma-idf.fr",
#     "cma.makangila@artisanat91.fr":"ornella.makangila@cma-idf.fr",
#     "cma.trony@artisanat91.fr":"ophelie.trony@cma-idf.fr",
#     "cma.pesquie@artisanat91.fr":"christelle.pesquie@cma-idf.fr",
#     "cma.heme@artisanat91.fr":"marielle.heme@cma-idf.fr",
#     "cma.puech@artisanat91.fr":"lea.puech@@cma-idf.fr",
#     "cma.charles@artisanat91.fr":"sandrine.charles@cma-idf.fr",
#     "cma.heintz@artisanat91.fr":"florence.heintzschaal@cma-idf.fr",
#     "cma.dao@artisanat91.fr":"corinne.dao@cma-idf.fr",
#     "cma.dasilva@artisanat91.fr":"marie.dasilva@cma-idf.fr",
#     "cma.lopez@artisanat91.fr":"lidia.lopez@cma-idf.fr",
#     "cma.rouxel@artisanat91.fr":"marie.cros@cma-idf.fr",
#     "cma.cros@artisanat91.fr":"marie.cros@cma-idf.fr",
#     "h.morvant@cm-27.fr":"hmorvant@cma-normandie.fr",
#     "hmille@cma-normandie.fr":"hmille@cma-normandie.fr",
#     "pascale.durand@cma-28.fr":"PDurand@cma-cvl.fr",
#     "tony.andre@cma-28.fr":"TAndre@cma-cvl.fr",
#     "stephanie.jeannesson@cma-28.fr":"SJeannesson@cma-cvl.fr",
#     "laurence.balogh-daroczy@cma-28.fr":"Lbalogh-Daroczy@cma-cvl.fr",
#     "nolwenn.lementec@cma-28.fr":"NLementec@cma-cvl.fr",
#     "carine.cloastre@cma29.fr":"carine.cloastre@cma-bretagne.fr",
#     "karine.plusquellec@cma29.fr":"karine.plusquellec@cma-bretagne.fr",
#     "rozenn.querret@cma29.fr":"rozenn.querret@cma-bretagne.fr",
#     "lenaig.guiziou@cma29.fr":"lenaig.guiziou@cma-bretagne.fr",
#     "charlotte.baron@cma29.fr":"charlotte.baron@cma-bretagne.fr",
#     "mari.pincivy@cma29.fr":"mari.pincivy@cma-bretagne.fr",
#     "charly.becker@cma29.fr":"charly.becker@cma-bretagne.fr",
#     "fraullet@cma-haute-marne.fr":"fraullet@cma-grandest.fr",
#     "aelkarmaoui@cma-haute-marne.fr":"aelkarmaoui@cma-grandest.fr",
#     "s.vennet@artisanat-comtois.fr":"svennet@artisanat-bfc.fr",
#     "flpioche@cma-nanterre.fr":"france-lise.pioche@cma-idf.fr",
#     "vfuchs@cma-nanterre.fr":"valerie.fuchs@cma-idf.fr",
#     "sturhan@cma-nanterre.fr":"silvia.turhan@cma-idf.fr",
#     "flemenn@cma-nanterre.fr":"florence.lemenn@cma-idf.fr",
#     "ppraeger@cma-nanterre.fr":"philippe.praeger@cma-idf.fr",
#     "jsenneville@cma-nanterre.fr":"jessy.senneville@cma-idf.fr",
#     "ibrindejonc@cma-rennes.fr":"isabelle.brindejonc@cma-bretagne.fr",
#     "mfcourcaud@cma-rennes.fr":"marie-france.courcaud@cma-bretagne.fr",
#     "nduchesne@cma-rennes.fr":"nelly.duchesne@cma-bretagne.fr",
#     "elegall@cma-rennes.fr":"emilie.legall@cma-bretagne.fr",
#     "bdelaplace@cma-rennes.fr":"berenice.delaplace@cma-bretagne.fr",
#     "iandro@cma-rennes.fr":"isabelle.andro@cma-bretagne.fr",
#     "achoplin@cma-rennes.fr":"alexandre.choplin@cma-bretagne.fr",
#     "idenis@cma-rennes.fr":"isabelle.denis@cma-bretagne.fr",
#     "cgornouvel@cma-rennes.fr":"caroline.gornouvel@cma-bretagne.fr",
#     "grillot@crm-bretagne.fr":"marie.grillot@cma-bretagne.fr",
#     "vgeffray@cma-rennes.fr":"veronique.geffray@cma-bretagne.fr",
#     "diane.erhel@cma-bretagne.fr":"diane.erhel@cma-bretagne.fr",
#     "mweryk@cma-rennes.fr":"mirrieme.weryk@cma-bretagne.fr",
#     "jl.gourin@cm-indre.fr":"JLGourin@cma-cvl.fr",
#     "i.decout@cm-indre.fr":"IDecout@cma-cvl.fr",
#     "cfremery@cm-tours.fr":"CFremery@cma-cvl.fr",
#     "cemonneau@cm-tours.fr":"Cemonneau@cma-cvl.fr",
#     "helene.marrillet@cma-isere.fr":"helene.marrillet@cma-auvergnerhonealpes.fr",
#     "patricia.fouillet@cma-isere.fr":"patricia.fouillet@cma-auvergnerhonealpes.fr",
#     "n.rivier@artisanat-comtois.fr":"nrivier@artisanat-bfc.fr",
#     "b.prost@artisanat-comtois.fr":"bprost@artisanat-bfc.fr",
#     "v.martinez@artisanat-comtois.fr":"vmartinez@artisanat-bfc.fr",
#     "valerie.monchal@cma-loire.fr":"valerie.monchal@cma-auvergnerhonealpes.fr",
#     "emmanuelle.quiblier@cma-loire.fr":"emmanuelle.quiblier@cma-auvergnerhonealpes.fr",
#     "perrine.mouillere@cma-loire.fr":"perrine.mouillere@cma-auvergnerhonealpes.fr",
#     "catherine.bertherat@cma-loire.fr":"catherine.bertherat@cma-auvergnerhonealpes.fr",
#     "amandine.rodamel@cma-loire.fr":"amandine.rodamel@cma-auvergnerhonealpes.fr",
#     "chadia.zoghbi@cma-loire.fr":"chadia.zoghbi@cma-auvergnerhonealpes.fr",
#     "franck.piat@cma-loire.fr":"franck.piat@cma-auvergnerhonealpes.fr",
#     "laurent.martinez@cma-loire.fr":"laurent.martinez@cma-auvergnerhonealpes.fr",
#     "philippe.lassabliere@cma-loire.fr":"philippe.lassabliere@cma-auvergnerhonealpes.fr",
#     "claire.dupin@cma-loire.fr":"claire.dupin@cma-auvergnerhonealpes.fr",
#     "beatrice.chalendard@cma-loire.fr":"beatrice.chalendard@cma-auvergnerhonealpes.fr",
#     "claire.soubeyrand@cma-loire.fr":"claire.soubeyrand@cma-auvergnerhonealpes.fr",
#     "edouard.chateau@cma-puydedome.fr":"edouard.chateau@cma-auvergnerhonealpes.fr",
#     "m.leboucq@cma-loiret.fr":"MLeboucq@cma-cvl.fr",
#     "p.rabin@cma-loiret.fr":"PRabin@cma-cvl.fr",
#     "e.guiet@cma-loiret.fr":"eguiet@cma-cvl.fr",
#     "ibouzy@cma-41.fr":"IBouzy@cma-cvl.fr",
#     "iautret@cma-41.fr":"IAutret@cma-cvl.fr",
#     "flegargasson@cma-41.fr":"FLegargasson@cma-cvl.fr",
#     "dpere@cma-41.fr":"Dpere@cma-cvl.fr",
#     "fferre@cma-41.fr":"FFerre@cma-cvl.fr",
#     "mpgosselin@artisanat50.fr":"mpgosselin@cma-normandie.fr",
#     "nhulmel@artisanat50.fr":"nhulmel@cma-normandie.fr",
#     "drouxel@artisanat50.fr":"drouxel@cma-normandie.fr",
#     "acolin@artisanat50.fr":"acolin@cma-normandie.fr",
#     "krobert@artisanat50.fr":"krobert@cma-normandie.fr",
#     "svleminckx@artisanat50.fr":"svleminckx@cma-normandie.fr",
#     "plepape@cma-meurthe-et-moselle.fr":"plepape@cma-grandest.fr",
#     "msoltner@cma-meurthe-et-moselle.fr":"msoltner@cma-grandest.fr",
#     "gjaisel@cma-meurthe-et-moselle.fr":"gjaisel@cma-grandest.fr",
#     "jchamant@cma-meurthe-et-moselle.fr":"jchamant@cma-grandest.fr",
#     "lbezai@cma-meurthe-et-moselle.fr":"lbezai@cma-grandest.fr",
#     "lthimouy@cma-meuse.fr":"lthimouy@cma-grandest.fr",
#     "tboutillot@cma-meuse.fr":"tboutillot@cma-grandest.fr",
#     "cvanderbeken@cma-meuse.fr":"cvanderbeken@cma-grandest.fr",
#     "emilie.pasgrimaud@cma-morbihan.fr":"emilie.pasgrimaud@cma-bretagne.fr",
#     "gwenola.vigouroux@cma-morbihan.fr":"gwenola.vigouroux@cma-bretagne.fr",
#     "yann.delafoulhouze@cma-morbihan.fr":"yann.delafoulhouze@cma-bretagne.fr",
#     "elaine.ledouairon@cma-morbihan.fr":"elaine.ledouairon@cma-bretagne.fr",
#     "veronique.larbaletrier@cma-morbihan.fr":"veronique.larbaletrier@cma-bretagne.fr",
#     "fanny.larmet@cma-morbihan.fr":"fanny.larmet@cma-bretagne.fr",
#     "nathalie.briand@cma-morbihan.fr":"nathalie.briand@cma-bretagne.fr",
#     "david.rolland@cma-morbihan.fr":"david.rolland@cma-bretagne.fr",
#     "philippe.geslin@cma-morbihan.fr":"philippe.geslin@cma-bretagne.fr",
#     "lorient@cma-morbihan.fr":"sylvie.leclerc@cma-bretagne.fr",
#     "cyril.lemero@cma-morbihan.fr":"cyril.lemero@cma-bretagne.fr",
#     "dominique.kersuzan@cma-morbihan.fr":"dominique.kersuzan@cma-bretagne.fr",
#     "ploermel@cma-morbihan.fr":"brigitte.oleron@cma-bretagne.fr",
#     "loica.hamery@cma-morbihan.fr":"loica.hamery@cma-bretagne.fr",
#     "choppe@crma-grandest.fr":"choppe@cma-grandest.fr",
#     "c.jehier@crma-centre.fr":"CJehier@cma-cvl.fr",
#     "mferraguti@artisanat-bourgogne.fr":"mferraguti@artisanat-bfc.fr",
#     "esalerno@artisanat-bourgogne.fr":"esalerno@artisanat-bfc.fr",
#     "pmorette@artisanat-bourgogne.fr":"pmorette@artisanat-bfc.fr",
#     "mlepommelec@artisanat-bourgogne.fr":"mlepommelec@artisanat-bfc.fr",
#     "fbrulard@cmai-calvados-orne.fr":"fbrulard@cma-normandie.fr",
#     "acabon@cmai-calvados-orne.fr":"acabon@cma-normandie.fr",
#     "hconception@cmai-calvados-orne.fr":"hconcdeption@cma-normandie.fr",
#     "manuel.varanda@crma-idf.fr":"manuel.varanda@cma-idf.fr",
#     "laurent.luce@cma-paris.fr":"laurent.luce@cma-idf.fr",
#     "emilie.berthelot@cma-paris.fr":"emilie.berthelot@cma-idf.fr",
#     "corine.lapalus@cma-paris.fr":"corine.lapalus@cma-idf.fr",
#     "lotfi.bagane@cma-paris.fr":"lotfi.bagane@cma-idf.fr",
#     "rosa.gondao@cma-paris.fr":"rosa.gondao@cma-idf.fr",
#     "samia.tounsi@cma-paris.fr":"samia.tounsi@cma-idf.fr",
#     "olivier.lenoble@cma-paris.fr":"olivier.lenoble@cma-idf.fr",
#     "angelique.klein@cma-paris.fr":"angelique.klein@cma-idf.fr",
#     "yves.drahi@cma-paris.fr":"yves.drahi@cma-idf.fr",
#     "sylvie.kohn@cma-paris.fr":"sylvie.kohn@cma-idf.fr",
#     "thibaut.dujardin@cma-paris.fr":"thibaut.dujardin@cma-idf.fr",
#     "isabelle.catrevaux@cma-paris.fr":"isabelle.catrevaux@cma-idf.fr",
#     "jenny.rabenandrasana@crma-idf.fr":"jenny.rabenandrasana@cma-idf.fr",
#     "stephanie.harand@crma-idf.fr":"stephanie.harand@cma-idf.fr",
#     "matthieu.beguin-billecocq@crma-idf.fr":"matthieu.beguin-billecocq@cma-idf.fr",
#     "samuel.cucherousset@crma-idf.fr":"samuel.cucherousset@cma-idf.fr ",
#     "laura.gasser@crma-idf.fr":"laura.gasser@cma-idf.fr ",
#     "yasmina.font-alba@crma-idf.fr":"yasmina.font-alba@cma-idf.fr ",
#     "marie-jeanne.moutoussamy@cma-paris.fr":"marie-jeanne.moutoussamy@cma-idf.fr",
#     "demet.konyali@cma-paris.fr":"demet.konyali@cma-idf.fr",
#     "christine.orseau@cma-paris.fr":"christine.orseau@cma-idf.fr",
#     "frederic.fourmy@crma-idf.fr":"frederic.fourmy@cma-idf.fr ",
#     "Nolwenn.Lachaux@crma-idf.fr":"Nolwenn.Lachaux@cma-idf.fr",
#     "rosa.gondao@cma-idf.fr":"rosa.gondao@cma-idf.fr",
#     "marie-liesse.couette@cma-idf.fr":"marie-liesse.couette@cma-idf.fr",
#     "h.ferfaille@cma-hautsdefrance.fr":"marie-liesse.couette@cma-idf.fr",
#     "catherine.stellmacher@cma-puydedome.fr":"catherine.stellmacher@cma-auvergnerhonealpes.fr",
#     "pchauvin@artisanat-bourgogne.fr":"pchauvin@artisanat-bfc.fr",
#     "ndanjean@artisanat-bourgogne.fr":"ndanjean@artisanat-bfc.fr",
#     "nisabelrepy@artisanat-bourgogne.fr":"nisabelrepy@artisanat-bfc.fr",
#     "nmeuret@artisanat-bourgogne.fr":"nmeuret@artisanat-bfc.fr",
#     "blevasseur@artisanat-bourgogne.fr":"blevasseur@artisanat-bfc.fr",
#     "rsabatier@artisanat-bourgogne.fr":"rsabatier@artisanat-bfc.fr",
#     "crenard@artisanat-bourgogne.fr":"crenard@artisanat-bfc.fr",
#     "herve.lagrange@cma77.fr":"herve.lagrange@cma-idf.fr",
#     "nicolas.fouquiau@cma77.fr":"nicolas.fouquiau@cma-idf.fr",
#     "laurent.bouvier@cma77.fr":"laurent.bouvier@cma-idf.fr",
#     "laurie.commault@cma77.fr":"laurie.commault@cma-idf.fr",
#     "sebastien.bonnelucq@cma77.fr":"sebastien.bonnelucq@cma-idf.fr",
#     "georgina.lagues-estrades@cma77.fr":"georgina.lagues-estrades@cma-idf.fr",
#     "valerie.virlouvet@cma77.fr":"valerie.virlouvet@cma-idf.fr",
#     "tiphaine.petitfils@cma77.fr":"tiphaine.petitfils@cma-idf.fr",
#     "geoffroy.debotte@cma77.fr":"geoffroy.debotte@cma-idf.fr",
#     "vera.hardoux@cma77.fr":"vera.hardoux@cma-idf.fr",
#     "virginie.randon@cma77.fr":"virginie.randon@cma-idf.fr",
#     "bruno.bonnet@cma77.fr":"bruno.bonnet@cma-idf.fr",
#     "melanie.goulet@cma77.fr":"melanie.goulet@cma-idf.fr",
#     "antenne.meaux@cma77.fr":"noemie.lagham@cma-idf.fr",
#     "nblondel@cma-normandie.fr":"nblondel@cma-normandie.fr",
#     "m.atchama@cma93.fr":"mickael.atchama@cma-idf.fr",
#     "s.gaudard@artisanat-comtois.fr":"sgaudard@artisanat-bfc.fr",
#     "sessahli@cma94.com":"saadia.essahli@cma-idf.fr",
#     "namere@cma94.com":"najla.amere@cma-idf.fr",
#     "jbaranton@cma94.com":"julie.baranton@cma-idf.fr",
#     "cdeniau@cma94.com":"christophe.deniau@cma-idf.fr",
#     "cot@cma95.fr":"isabelle.cot@cma-idf.fr",
#     "hurion@cma95.FR":"valerie.hurion@cma-idf.fr",
#     "cojandassamy@cma95.fr":"yves.cojandassamy@cma-idf.fr",
#     "desmaris@cma95.fr":"lauriane.desmaris@cma-idf.fr",
#     "noel@cma95.fr":"sandra.noel@cma-idf.fr",
#     "silvestre@cma95.fr":"grace.silvestre@cma-idf.fr",
#     "glon@cma95.fr":"catherine.glon@cma-idf.fr",
#     "domingues@cma95.fr":"paula.domingues@cma-idf.fr",
#     "eflorentin@cma-vosges.fr":"eflorentin@cma-grandest.fr",
#     "cbrousse@cma-vosges.fr":"cbrousse@cma-grandest.fr",
#     "ralias@artisanat-bourgogne.fr":"ralias@artisanat-bfc.fr",
#     "cremy@artisanat-bourgogne.fr":"cremy@artisanat-bfc.fr",
#     "sandrine.sibillotte@cma77.fr":"sandrine.sibillotte@cma-idf.fr",
#     "ctourlier@artisanat-bourgogne.fr":"ctourlier@artisanat-bfc.fr",
#     "ppinna@artisanat-bourgogne.fr":"ppinna@artisanat-bfc.fr",
#     "ncordier@artisanat-bourgogne.fr":"ncordier@artisanat-bfc.fr",
#     "m.vattaire@cm-yvelines.fr":"maupessa.vattaire@cma-idf.fr",
#     "m.bordier@cm-yvelines.fr":"morgane.bordier@cma-idf.fr",
#     "l.leblanc@cm-yvelines.fr":"lucie.leblanc@cma-idf.fr"
# }

users_list_to_remail = {
    "cma.puech@artisanat91.fr":"lea.puech@cma-idf.fr",
    "matthieu.beguin-billecocq@crma-idf.fr":"matthieu.beguinbillecocq@cma-idf.fr",
    "marie-jeanne.moutoussamy@cma-paris.fr":"marie-jeanne.moutoussamydeflore@cma-idf.fr",
    "georgina.lagues-estrades@cma77.fr":"georgina.laguesestrades@cma-idf.fr",
    "antenne.meaux@cma77.fr":"noemie.langham@cma-idf.fr",
    "hconception@cmai-calvados-orne.fr":"hconception@cma-normandie.fr",
    "x.ravel@cma-drome.fr":"xavier.ravel@cma-auvergnerhonealpes.fr",
    "l.gourdon@cma-drome.fr":"ludovic.gourdon@cma-auvergnerhonealpes.fr",
    "n.ammarene@cma-drome.fr":"nicolas.ammarene@cma-auvergnerhonealpes.fr",
    "n.lapassat@cma-drome.fr":"nathalie.lapassat@cma-auvergnerhonealpes.fr",
    "m.schroder@cma-drome.fr":"marlène.schroder@cma-auvergnerhonealpes.fr",
    "e.mindren@cma-drome.fr":"estelle.mindren@cma-auvergnerhonealpes.fr",
    "l.cane@cma-drome.fr":"laetitia.cane@cma-auvergnerhonealpes.fr"
}

for user_email in users_list_to_remail:
    log.info("[WUL] treating user : {}".format(user_email))
    try :
        user = User.objects.get(email=user_email)
        user_profile = UserProfile.objects.get(user_id=user.id)
        user.email = users_list_to_remail[user_email]
        user.save()
        user_profile.save()
        log.info("[WUL] new email set : {}".format(users_list_to_remail[user_email]))
    except:
        log.error("[WUL] cannot set this new email : {} for user {}, this one cannot be found in DB".format(users_list_to_remail[user_email],user_email))


# sudo -H -u edxapp /edx/bin/python.edxapp /edx/app/edxapp/edx-microsite/e-formation-artisanat/utils/change_email_user.py